//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iosu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Partner = new HashSet<Partner>();
        }
    
        public long Id { get; set; }
        public string AgentFullName { get; set; }
        public string Adress { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<Partner> Partner { get; set; }
    }
}
