//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iosu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ORDERS = new HashSet<Order>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long ManufacturerId { get; set; }
        public long UnitPrice { get; set; }
        public long Amount { get; set; }
    
        internal virtual ICollection<Order> ORDERS { get; set; }
        internal virtual Partner PARTNERS { get; set; }
    }
}
